In [1]:
import pandas as pd
import numpy as np
from scipy.stats import kurtosis, iqr, skew, zscore
import matplotlib.pyplot as plt
import plotly.express as px     # histogram, box-plot
import seaborn as sns
import math

In [2]:
df = pd.read_csv("C:/Users/go27s/OneDrive/Documents/Udemy/Statistics and Probability/Statistics/bigmartsales.csv")

In [3]:
df.head()

Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
0           FDA15         9.30          Low Fat         0.016047   
1           DRC01         5.92          Regular         0.019278   
2           FDN15        17.50          Low Fat         0.016760   
3           FDX07        19.20          Regular         0.000000   
4           NCD19         8.93          Low Fat         0.000000   

               Item_Type  Item_MRP Outlet_Identifier  \
0                  Dairy  249.8092            OUT049   
1            Soft Drinks   48.2692            OUT018   
2                   Meat  141.6180            OUT049   
3  Fruits and Vegetables  182.0950            OUT010   
4              Household   53.8614            OUT013   

   Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0                       1999      Medium               Tier 1   
1                       2009      Medium               Tier 3   
2                       1999      Medium               Tier 1   
3                       1998         NaN               Tier 3   
4                       1987        High               Tier 3   

         Outlet_Type  Item_Outlet_Sales  
0  Supermarket Type1          3735.1380  
1  Supermarket Type2           443.4228  
2  Supermarket Type1          2097.2700  
3      Grocery Store           732.3800  
4  Supermarket Type1           994.7052

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Item_Identifier            8523 non-null   object 
 1   Item_Weight                7060 non-null   float64
 2   Item_Fat_Content           8523 non-null   object 
 3   Item_Visibility            8523 non-null   float64
 4   Item_Type                  8523 non-null   object 
 5   Item_MRP                   8523 non-null   float64
 6   Outlet_Identifier          8523 non-null   object 
 7   Outlet_Establishment_Year  8523 non-null   int64  
 8   Outlet_Size                6113 non-null   object 
 9   Outlet_Location_Type       8523 non-null   object 
 10  Outlet_Type                8523 non-null   object 
 11  Item_Outlet_Sales          8523 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 799.2+ KB


In [ ]:
# Calculate the Measures of Central Tendency: mean, median, mode for Item_MRP

In [51]:
df[['Item_MRP', 'Item_Outlet_Sales']].mean()

Item_MRP              140.992782
Item_Outlet_Sales    2181.288914
dtype: float64

In [52]:
df[['Item_MRP', 'Item_Outlet_Sales']].median() # at least half of the item is sold for $143 dollars

Item_MRP              143.0128
Item_Outlet_Sales    1794.3310
dtype: float64

In [53]:
df[['Item_MRP', 'Item_Outlet_Sales']].mode()

Item_MRP  Item_Outlet_Sales
0  172.0422            958.752

In [ ]:
Calculate Measures of Spread: Range, Variance, Std

In [40]:
def get_range(x):
    x_range = np.max(x) - np.min(x)
    return x_range


# def get_variance(x):
#     x_mean = np.sum(x) / len(str(x))
#     x_deviation = [(x - x_mean)**2 for i in x]
#     x_variance = np.sum(x_deviation) / len(str(x))
#     return x_variance


# def get_std(x):
#     x_var = get_variance(x)
#     x_std = np.sqrt(x_var)
#     return x_std


def find_outliers_iqr(x):
    Q1 = x.quantile(0.25)
    Q3 = x.quantile(0.75)
    IQR = Q3 - Q1
    outliers = x[((x < (Q1 - 1.5) * IQR) | (x > (Q3 + 1.5) * IQR))]
    return outliers


def find_outliers_zscore(x):
    x_mean = np.mean(x)
    x_std = get_std(x)
    x_zscore = (x - x_mean) / x_std
    
    return x_zscore

In [16]:
df['Item_MRP'].min()

31.29

In [17]:
df['Item_MRP'].max()

266.8884

In [13]:
get_range(df['Item_MRP']) # data is spread out considering the median value is 143.0128

235.5984

In [58]:
df[['Item_MRP', 'Item_Outlet_Sales']].var()

Item_MRP             3.878184e+03
Item_Outlet_Sales    2.912141e+06
dtype: float64

In [55]:
#get_std(df['Item_MRP'])
df[['Item_MRP', 'Item_Outlet_Sales']].std()   # high std -> the data is spread out around the mean

Item_MRP               62.275067
Item_Outlet_Sales    1706.499616
dtype: float64

In [62]:
skew(df[['Item_MRP', 'Item_Outlet_Sales']], axis =0)

array([0.12717988, 1.17732335])

In [19]:
kurtosis(df['Item_Outlet_Sales'], fisher=False)

4.614224991590342

In [20]:
kurtosis(df['Item_Outlet_Sales'], fisher=True)

1.6142249915903424

In [28]:
find_outliers_zscore(df['Item_MRP'])

0       3.833812e-05
1      -3.266831e-05
2       2.202764e-07
3       1.448110e-05
4      -3.069807e-05
            ...     
8518    2.590569e-05
8519   -1.156868e-05
8520   -1.968421e-05
8521   -1.333866e-05
8522   -2.308600e-05
Name: Item_MRP, Length: 8523, dtype: float64

In [80]:
df['Item_MRP_zscore'] = df['Item_MRP']  - df['Item_MRP'].mean()
df['z'] = zscore(df['Item_Outlet_Sales'])

np.where(abs(z > 3))
#df['Item_MRP_zscore'].min()  # -109
#df['Item_MRP_zscore'].max()  # 125
#df_histogram_ss = px.histogram(df, x = 'Item_MRP_zscore')
#.show()

(array([ 130,  145,  276,  304,  333,  373,  456,  472,  661,  694,  753,
         809,  935,  991,  997, 1009, 1138, 1254, 1450, 1506, 1859, 1998,
        2109, 2216, 2238, 2293, 2516, 2535, 2776, 3083, 3087, 3098, 3154,
        3234, 3286, 3407, 3667, 3709, 3720, 3757, 4289, 4346, 4349, 4676,
        4681, 4772, 4888, 4961, 4991, 5065, 5177, 5185, 5223, 5315, 5500,
        5550, 5619, 5752, 5799, 5812, 5977, 6000, 6134, 6334, 6409, 6537,
        6541, 6606, 6886, 6993, 7016, 7076, 7188, 7191, 7236, 7256, 7302,
        7343, 7560, 7562, 7609, 7690, 7752, 7816, 7826, 7930, 8039, 8201,
        8245, 8447], dtype=int64),)

In [ ]:
#Remove Outliers using zscore

In [77]:
df.shape

(8523, 16)

In [82]:
df.drop(df[df['z'] > 3].index, inplace = True)

In [83]:
df.shape

(8433, 17)

In [50]:
find_outliers_zscore(df['Item_Outlet_Sales'])
df['Item_Outlet_Sales_zscore'] = df['Item_Outlet_Sales']  - df['Item_Outlet_Sales'].mean()
df_histogram_ss = px.histogram(df, x = 'Item_Outlet_Sales_zscore')
df_histogram_ss.show()

In [49]:
df['Item_Outlet_Sales_iqr'] = find_outliers_iqr(df['Item_Outlet_Sales'])
df_histogram_ss = px.histogram(df, x = 'Item_Outlet_Sales_iqr')
df_histogram_ss.show()

In [48]:
df['Item_MRP_iqr'] = find_outliers_iqr(df['Item_MRP'])
#df['Item_MRP_iqr'].min()  # -109
#df['Item_MRP_iqr'].max()  # 125
#df[abs(df['Item_MRP_zscore']) > 1.5]
df_histogram_ss = px.histogram(df, x = 'Item_MRP_iqr')
df_histogram_ss.show()

In [61]:
iqr(df[['Item_MRP', 'Item_Outlet_Sales']], axis = 0)

array([  91.8172, 2267.049 ])