In [1]:
import numpy as np

In [2]:
# Numpy arrays: 1 dimensional vectors and 2 dimensional matricies

In [3]:
my_list = [1,2,3]

In [4]:
my_list

[1, 2, 3]

In [6]:
arr = np.array(my_list)

In [7]:
arr

array([1, 2, 3])

In [8]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
my_mat  # 1 dimensional array

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
# cast a list of lists to array
np.array(my_mat) # 2 dimensional array meaning two sets of brackets

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((5,5))  # tuples

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.linspace(0,5,10)  # return 10 numbers evenly spaced from 0 to 5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [16]:
# Identity matrix

In [17]:
np.eye(4)  # 4 columns and 4 rows

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
# Randon numbers

In [19]:
np.random.rand(5)

array([0.12812216, 0.47310597, 0.30950266, 0.68938319, 0.24589435])

In [20]:
np.random.rand(5,5)

array([[0.24743385, 0.07729623, 0.7712023 , 0.45237951, 0.07681145],
       [0.10033771, 0.21807066, 0.9332859 , 0.51096425, 0.95468821],
       [0.67381664, 0.34079304, 0.15569661, 0.73795519, 0.90459021],
       [0.3995228 , 0.14777304, 0.17584817, 0.98335279, 0.22721754],
       [0.3097707 , 0.12767305, 0.35116351, 0.23603861, 0.61429483]])

In [3]:
# standard normal distribution
np.random.randn(4,4)

array([[-0.07628643,  1.2098017 ,  0.0360186 , -1.5171064 ],
       [ 0.08613352, -0.23357742, -0.08919868, -2.07469126],
       [-0.19841552, -1.79179907,  0.29140977,  0.0109538 ],
       [ 1.61165277,  0.85663511, -2.41698871, -1.29415063]])

In [4]:
# get a random int between 0 and 100, incl 0 and excl 100
np.random.randint(0,100)

90

In [5]:
# 10 random integers, incl 1 and excl 100
np.random.randint(1,100,10)

array([96, 68, 30, 88, 85,  6, 80, 25, 43, 85])

In [8]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [9]:
ranarr = np.random.randint(0,50,10)
ranarr

array([11, 42,  0, 16, 43,  1, 34,  3,  4, 25])

In [10]:
# reshape array

In [11]:
arr.reshape(5,5)   # no of rows * no of columns is equal to the no of elements in the array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
ranarr

array([11, 42,  0, 16, 43,  1, 34,  3,  4, 25])

In [12]:
ranarr.max()

43

In [13]:
ranarr.min()

0

In [14]:
# return index location of the max value

In [15]:
ranarr.argmax()

4

In [17]:
ranarr.argmin()

2

In [19]:
arr.shape # 1 dimensional

(25,)

In [20]:
ranarr.shape   # 1 dimensional

(10,)

In [21]:
r = arr.reshape(5,5)
r.shape    # 2 dimensional

(5, 5)

In [22]:
arr.dtype

dtype('int32')