In [1]:
import numpy as np

In [4]:
arr = np.arange(4,21)
arr

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
#return a value at index 8
arr[8]

12

In [6]:
# 1 starting index, 5 ending index
arr[1:5]

array([5, 6, 7, 8])

In [7]:
# up to index 6
arr[:6]

array([4, 5, 6, 7, 8, 9])

In [8]:
# start at index 5 up to the end
arr[5:]

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [10]:
# replace first 3 values with 100
arr[:3] = 100
arr

array([100, 100, 100,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,
        17,  18,  19,  20])

In [11]:
arr = np.arange(4,21)
arr

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [12]:
# taking a slice of arr, which isn't a copy!!!
slice_of_arr = arr[:6]
slice_of_arr

array([4, 5, 6, 7, 8, 9])

In [13]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [14]:
arr

array([99, 99, 99, 99, 99, 99, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [15]:
# to make a copy of a numpy array use copy() method. This way the original array won't be affected!!!
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [16]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100])

In [17]:
arr

array([99, 99, 99, 99, 99, 99, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [18]:
# 2 dimensional arrays

In [19]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [20]:
# 1st row and 1st column
arr_2d[0][0]

5

In [21]:
# entire row
arr_2d[0]

array([ 5, 10, 15])

In [22]:
arr_2d[1][1]

25

In [23]:
# using comma instead of brackets
arr_2d[2,1]

40

In [24]:
# up to row 2, from column 2 onwards
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [25]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [27]:
arr_2d[1,0:3]

array([20, 25, 30])

In [28]:
# Conditional Selection

In [30]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [33]:
# get only results where bool_arr is True
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [34]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [35]:
arr[arr<3]

array([0, 1, 2])

In [38]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [42]:
arr_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])