In [ ]:
# Series.tolist()                 Convert Series to a list

# np.arange(10)
# np.arange(4,10)
# np.arange(10,100,10)

# series = series.astype('int')       Convert Series type

# df.append(pd.Series({'BBT': 25.5, 'F51': 19.2}))          Add elements to Series

# stocks = {'PLW': 387.00, 'CDR': 339.5, 'TEN': 349.5, '11B': 391.0, 'BBT': 25.5, 'F51': 19.2}
# quotations = pd.Series(data=stocks)
# quotations_df = pd.DataFrame(quotations).reset_index()                       reset_index
# quotations_df.columns = ['ticker', 'price']                                  assign columns


# companies.set_index('company', inplace=True)                                 set_index to a different column

In [ ]:
# Convert a Series to a list

In [1]:
import pandas as pd
import numpy as np

In [5]:
stocks = {'PLW': 387.00, 'CDR': 339.5, 'TEN': 349.5, '11B': 391.0}
quotations = pd.Series(data=stocks)

In [6]:
quotations.to_list()

[387.0, 339.5, 349.5, 391.0]

In [18]:
np1 = np.arange(10,100,10)
np1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [19]:
np2 = np.arange(101,110)
np2

array([101, 102, 103, 104, 105, 106, 107, 108, 109])

In [20]:
pd.Series(data=np1, index=np2)

101    10
102    20
103    30
104    40
105    50
106    60
107    70
108    80
109    90
dtype: int32

In [21]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [22]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [27]:
series = pd.Series(['001', '002', '003', '004'], list('abcd'))
series

a    001
b    002
c    003
d    004
dtype: object

In [29]:
series.astype()
series

a    001
b    002
c    003
d    004
dtype: object

In [32]:
series = series.astype('int')
series

a    1
b    2
c    3
d    4
dtype: int32

In [33]:
stocks = {'PLW': 387.00, 'CDR': 339.5, 'TEN': 349.5, '11B': 391.0}
quotations = pd.Series(data=stocks)
quotations

PLW    387.0
CDR    339.5
TEN    349.5
11B    391.0
dtype: float64

In [43]:
quotations = quotations.append(pd.Series({'BBT': 25.5, 'F51': 19.2}))
quotations

C:\Users\go27s\AppData\Local\Temp\ipykernel_6724\4241859563.py:1: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  quotations = quotations.append(pd.Series({'BBT': 25.5, 'F51': 19.2}))


PLW    387.0
CDR    339.5
TEN    349.5
11B    391.0
BBT     25.5
F51     19.2
BBT     25.5
F51     19.2
dtype: float64

In [49]:
stocks = {'PLW': 387.00, 'CDR': 339.5, 'TEN': 349.5, '11B': 391.0, 'BBT': 25.5, 'F51': 19.2}
quotations = pd.Series(data=stocks)
quotations

PLW    387.0
CDR    339.5
TEN    349.5
11B    391.0
BBT     25.5
F51     19.2
dtype: float64

In [53]:
quotations_df = pd.DataFrame(quotations).reset_index()
quotations_df.columns = ['ticker', 'price']
quotations_df

ticker  price
0    PLW  387.0
1    CDR  339.5
2    TEN  349.5
3    11B  391.0
4    BBT   25.5
5    F51   19.2

In [67]:
data = {'company': ('Amazon', 'Microsoft', 'Facebook'), 'price': (2375.0, 178.6, 179.2), 'ticker': ('AMZN.US', 'MSFT.US', 'FB.US')}
data

{'company': ('Amazon', 'Microsoft', 'Facebook'),
 'price': (2375.0, 178.6, 179.2),
 'ticker': ('AMZN.US', 'MSFT.US', 'FB.US')}

In [68]:
companies = pd.DataFrame(data)
companies

company   price   ticker
0     Amazon  2375.0  AMZN.US
1  Microsoft   178.6  MSFT.US
2   Facebook   179.2    FB.US

In [69]:
type(companies)

pandas.core.frame.DataFrame

In [70]:
companies

company   price   ticker
0     Amazon  2375.0  AMZN.US
1  Microsoft   178.6  MSFT.US
2   Facebook   179.2    FB.US

In [71]:
companies.set_index('company', inplace=True)
companies

price   ticker
company                   
Amazon     2375.0  AMZN.US
Microsoft   178.6  MSFT.US
Facebook    179.2    FB.US