In [ ]:
# Numpy array is a row-and-column data structure that we use to store numeric/boolean data.
# Numpy have axes. For 1-dimesional arrays, there is 1 axis, axis-0, which points horizontally. For 2-dimensional, axis-0 points
# downwards and axis-1 point horizontally

# np.all() checks if all elements meet some condition or evaluate as True
# np.all(A > 4)  --> False


# Use all() when you need to check a long series of AND conditions. When ALL conditions have to be met
# Use any() when you need to check a long series of OR conditions. When ANY condition has be met
# if any(conditions):
     # Do something here
     # ...
        

# Check for nan values
# np.isnan(A)


# Check if the following arrays are equal (element-wise)
# np.allclose([A], [B])


# Check if the following arrays are equal (value-wise):
# A == B     OR    np.equal(A,B)


# Check which numbers (element-wise) from the A array are greater than numbers from the B array
# A > B      OR    np.greater(A,B)


# Using Numpy, create an array 10x10 filled with number 255 and set the data type to float.
# np.ones(shape=(10,10), dtype='float') * 255
# OR
# np.full(shape=(10, 10), fill_value=255, dtype='float')

# Functions
# np.all()
# np.any()
# np.isnan()
# np.allclose() 
# np.equal()    A == B
# np.greater()  A > B
# np.zeros()
# np.ones()
# np.full()

In [3]:
import numpy as np

In [4]:
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

D = np.array([0.1, 0.3])

In [5]:
np.all(A > 4)

False

In [7]:
print('A: ', np.all(A))
print('B: ', np.all(B))
print('C: ', np.all(C))
print('D: ', np.all(D))

A:  True
B:  False
C:  False
D:  True


In [12]:
# create a list for zip() first

for name, array in zip(list('ABCD'), [A, B, C, D]):
    print(name, np.all(array))

A True
B False
C False
D True


In [13]:
# Exercise 2

In [14]:
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

In [15]:
np.all(A,axis=1)

array([ True,  True])

In [16]:
for name, array in zip(list('ABC'), [A, B, C]):
    print(f"{name}: {np.all(array, axis=1)}")

A: [ True  True]
B: [ True False]
C: [False  True]


In [17]:
# Exercise 3

In [18]:
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])

In [20]:
for name, array in zip(list('ABCD'), [A, B, C, D]):
    print(f"{name}: {np.any(array)}")

A: False
B: True
C: True
D: True


In [21]:
# Exercise 4

In [22]:
for name, array in zip(list('ABCD'), [A, B, C, D]):
    print(f"{name}: {np.any(array, axis=0)}")

A: [False False False]
B: [False  True False]
C: [ True False False]
D: [ True False]


In [23]:
# Exercise 5

In [24]:
A = np.array([[3, 2, 1, np.nan],
              [5, np.nan, 1, 6]])

In [26]:
np.isnan(A)

array([[False, False, False,  True],
       [False,  True, False, False]])

In [27]:
# Exercise 6

In [28]:
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.39999999, 0.5000001, 0.3])

In [29]:
# Check if the following arrays are equal (element-wise):
np.allclose([A], [B])

True

In [ ]:
# Exercise 7

In [30]:
# Check if the following arrays are equal (value-wise):
A == B

array([False, False,  True])

In [31]:
np.equal(A,B)

array([False, False,  True])

In [32]:
# Exercise 8

In [34]:
A = np.array([0.4, 0.5, 0.3, 0.9])
B = np.array([0.38, 0.51, 0.3, 0.91])

In [35]:
# Check which numbers (element-wise) from the A array are greater than numbers from the B array
A > B

array([ True, False, False, False])

In [36]:
np.greater(A,B)

array([ True, False, False, False])

In [37]:
# Exercise 9

In [42]:
# Using Numpy create a 4x4 array filled with zeros (set data type to int)
np.zeros(shape=(4,4), dtype='int')      # 4 rows, 4 columns

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [43]:
# Exercise 10

In [44]:
# Using Numpy, create an array 10x10 filled with number 255 and set the data type to float.
np.ones(shape=(10,10), dtype='float') * 255

array([[255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.]])

In [45]:
np.full(shape=(10, 10), fill_value=255, dtype='float')

array([[255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.]])