In [ ]:
# create a one-dimensional array of all two-digit numbers
# np.arange(10,100)


# Create a 6x6 two-dimensional array - identity matrix with int data type
# np.eye(N=6,M=6, dtype='float')


# Create a one-dimensional array consisting of 30 pseudo-randomly generated values
# np.random.rand(30)


# Print elements of an array
# for i in np.nditer(A):
#     print(i)


# Methods
# np.arange(10,100)             Return evenly spaced values within a given interval.
# np.arange().reshape()
# np.eye()                Return a 2-D array with ones on the diagonal and zeros elsewhere.
# np.random.rand(3,2)     Create random values, 3 rows 2 columns
# np.random.randn(2,4)    Return a sample form the standard normal distribution 
# np.nditer()             Iterate though the elements of an array
# np.linspace(start=0,stop=1,11)     1 dim array of 11 elements equally distributed
# np.random.choice(a=range(1,50), size=6, replace=False)   Generates a random sample from a agiven 1-D array
# np.random.choice(5, 3)
# np.diag(np.arange(6))    Extract a diagonal or construct a diagonal array

In [1]:
import numpy as np

In [ ]:
# Exercise 11

In [2]:
# create a one-dimensional array of all two-digit numbers
np.arange(10,100)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [3]:
# Exercise 12

In [4]:
# shape of this array is (9, 10)
np.arange(10,100).reshape(9,10)

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [5]:
# Exercise 13

In [8]:
# Create a 6x6 two-dimensional array - identity matrix with int data type
np.eye(N=6, M=6, dtype='int')

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [9]:
# Exercise 14

In [16]:
# Set the random seed to 10. Then using Numpy create a one-dimensional array consisting of 30 pseudo-randomly generated values 
# from the uniform distribution [0,1)

np.random.seed = 10

np.random.rand(30)

array([0.04942386, 0.95258949, 0.76623169, 0.39568648, 0.96875472,
       0.34707157, 0.29719269, 0.38966109, 0.07434185, 0.46802295,
       0.4006606 , 0.47053114, 0.03806851, 0.98836903, 0.3554886 ,
       0.42602756, 0.86136587, 0.65036821, 0.14374968, 0.56492686,
       0.47983014, 0.07444342, 0.29695901, 0.18233297, 0.62573588,
       0.94683422, 0.73585938, 0.71186881, 0.73667338, 0.32841485])

In [2]:
# Exercise 15

In [3]:
# create a two-dimensional array with the shape (10, 4) pseudo-randomly generated values from 
# the standard normal distribution N(0,1)

np.random.seed = 20

np.random.randn(10, 4)

array([[ 1.86813774,  2.15345504, -0.01943804, -0.11010937],
       [ 1.94667628,  1.86969308,  1.64364406,  2.99401077],
       [-0.00336749,  0.14243692,  1.4028942 ,  1.10266306],
       [ 1.19967497, -0.06960494, -0.54489489,  2.57777121],
       [ 0.57663413, -0.77557148, -1.3296798 , -1.40739554],
       [-1.26019894, -0.91901161,  0.54001693, -0.94301921],
       [ 0.99979238, -0.28807899, -1.14219631, -1.13849429],
       [ 0.34241397, -1.7262832 , -0.46832416,  1.68505451],
       [-0.16613469, -0.72576507,  0.13376755,  0.20467053],
       [-1.24592636, -0.56377682, -0.20452194,  0.51600294]])

In [4]:
# Exercise 16

In [5]:
np.random.seed=30
np.random.randn(10,4)

array([[-0.70461002, -0.56330189,  1.72428341,  0.02529715],
       [ 0.28854118, -0.85735222,  0.02761593,  0.80734511],
       [ 1.43569628, -1.19111858,  1.85312426,  0.49564102],
       [-0.35658602, -0.80254531, -0.39946212, -1.52016309],
       [-0.12717228, -1.32357553, -1.42558464,  0.09268221],
       [ 2.36747891,  0.50743985, -1.46574934,  0.83948335],
       [-1.07671586,  0.62773808, -0.16308493, -0.72204932],
       [-1.48848659,  0.39044017, -0.33891299,  0.06571546],
       [ 1.21300052,  2.16468074, -0.96099221, -2.2483052 ],
       [-0.47961504,  1.04096486, -0.93667012,  0.81942753]])

In [6]:
# Exercise 17

In [7]:
A = np.array([[1, 4, 3],
              [5, 2, 6]])

In [11]:
for i in np.nditer(A):
    print(i)

1
4
3
5
2
6


In [12]:
# Exercise 18

In [13]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [14]:
# Exercise 19

In [15]:
np.random.choice(a=range(1,50), size=6, replace=False)

array([44, 43, 10,  2, 45, 25])

In [16]:
# Exercise 20

In [17]:
np.diag(np.arange(6))

array([[0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5]])