In [1]:
# https://www.youtube.com/watch?v=W-0-u6XVbE4&ab_channel=Simplilearn

In [2]:
from sklearn.neural_network import MLPRegressor   # linear regression model
from sklearn.metrics import mean_absolute_error   # how well the model fits
import numpy as np
from sklearn.model_selection import validation_curve   # looking at the curve
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt
from sklearn.model_selection import KFold
np.random.seed(0)
plt.style.use('ggplot')

%matplotlib inline

In [3]:
iris = load_iris()
X, y = iris.data, iris.target

In [4]:
print(X[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [5]:
print(y[:5])

[0 0 0 0 0]


AttributeError: head